id: P007897
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB25060
  title: གསུང་འབུམ། འུག་ཡུག་པ་རིགས་པའི་སེངྒེ
  author: ''
  volumes:
    3450b45db42a4befa0cdb9277b3956f1:
      image_group_id: I1PD36273
      title: ''
      volume_number: 1
      total_pages: 207
    2ce0d251fb7b42348f3634debbd8d356:
      image_group_id: I1PD36274
      title: ''
      volume_number: 2
      total_pages: 244
    0b17f078e2e1450e80c8d20fe4e6859d:
      image_group_id: I1PD36275
      title: ''
      volume_number: 3
      total_pages: 265
ebook_metadata:
  title: གསུང་འབུམ། འུག་ཡུག་པ་རིགས་པའི་སེངྒེ
  author: ''
  sku: P007897
  cover: cover.jpg
  layers:
  - pagination
