id: I3C60F6E6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:05:25+00:00'
last_modified: '2022-06-09T07:12:24.495243+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB25060
  title: གསུང་འབུམ། འུག་ཡུག་པ་རིགས་པའི་སེངྒེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1260':
      image_group_id: I1PD36273
      title: Volume 1 of gsung 'bum/_'ug yug pa rigs pa'i seng ge
      total_pages: 207
      order: 1
      base_file: 1260.txt
    BA1A:
      image_group_id: I1PD36274
      title: Volume 2 of gsung 'bum/_'ug yug pa rigs pa'i seng ge
      total_pages: 244
      order: 2
      base_file: BA1A.txt
    F867:
      image_group_id: I1PD36275
      title: Volume 3 of gsung 'bum/_'ug yug pa rigs pa'i seng ge
      total_pages: 265
      order: 3
      base_file: F867.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
